In [34]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split


df = pd.read_csv('wine.csv')

df.describe()
df.drop_duplicates()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,bad
1,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,bad
2,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,bad
3,11.2,0.280,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,good
5,7.4,0.660,0.00,1.8,0.075,13.0,40.0,0.99780,3.51,0.56,9.4,bad
...,...,...,...,...,...,...,...,...,...,...,...,...
1593,6.8,0.620,0.08,1.9,0.068,28.0,38.0,0.99651,3.42,0.82,9.5,good
1594,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,bad
1595,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2,good
1597,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,bad
1598,6.0,0.310,0.47,3.6,0.067,18.0,42.0,0.99549,3.39,0.66,11.0,good

In [19]:

df.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,bad
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,bad
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,bad
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,good
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,bad

In [35]:
df['quality']=df.quality.replace({"bad":0,"good":1})
df.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,0
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,0
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,0
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,1
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,0

In [36]:
y = df.quality.replace({"bad":0,"good":1})

In [37]:
def sigmoid(z):
    return 1 / (1 + np.exp(-z))

def hypothesis(X, t):
    z = np.dot(t, X.T)
    return (sigmoid(z) - 0.0000001)


#X list of features
def cost(X, y, t):
    y1 = hypothesis(X, t)
    return -(1/len(X)) * np.sum(y*np.log(y1) + (1-y)*np.log(1-y1))


def gradient_descent(X, y, t, alpha, epochs):
    m =len(X)
    J = [cost(X, y, t)] 
    for i in range(0, epochs):
        h = hypothesis(X, t)
        for i in range(0, len(X.columns)):
            t[i] -= (alpha/m) * np.sum((h-y)*X.iloc[:, i])
        J.append(cost(X, y, t))
    return J, t

def predict(X, y, t, a, epochs):
    J, t = gradient_descent(X, y, t, a, epochs) 
    h = hypothesis(X, t)
    for i in range(len(h)):
        h[i]=1 if h[i]>=0.5 else 0
    y = list(y)
    acc = np.sum([y[i] == h[i] for i in range(len(y))])/len(y)
    return J, acc

In [48]:
X = df.drop('quality',axis=1)
#y = df['quality']
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.2,random_state=0)




theta = [0.5]*len(X_train.columns)
J, acc = predict(X_train, y_train, theta, 0.0001, 80000)

print(acc*100)

/var/folders/yj/4x23rrnj341_bnx_b11lgjkw0000gn/T/ipykernel_54700/1691007049.py:12: RuntimeWarning: invalid value encountered in log
  return -(1/len(X)) * np.sum(y*np.log(y1) + (1-y)*np.log(1-y1))

63.721657544957

In [54]:
theta = [0.5]*len(X_test.columns)
J, acc_test = predict(X_test, y_test, theta, 0.0001, 80000)
print(acc_test*100)

#accuracy of the test model

/var/folders/yj/4x23rrnj341_bnx_b11lgjkw0000gn/T/ipykernel_54700/1691007049.py:12: RuntimeWarning: invalid value encountered in log
  return -(1/len(X)) * np.sum(y*np.log(y1) + (1-y)*np.log(1-y1))

64.6875